# Generated by test/verification/autoarima/bulk/gen_julia_test.py -- do not edit by hand.
#
# Ground truth: real pmdarima.auto_arima (2.0.4, pip-installed) AND real R
# forecast::auto.arima (forecast IS installed and reachable this session, confirmed
# directly -- not the CRAN-unreachable boundary noted in earlier stages) on 20 synthetic
# series regenerated from the Stage 6.8 handoff's own generating code
# (handoff/stage-6.8-autoarima-handoff.md section 6). Capped at 20 cases per explicit
# instruction; extend N_CASES in gen_and_fit_python.py and regenerate for more.
#
# Accuracy criterion (handoff section 6): match against each reference's own
# selected_order on identical data, not the unknowable true generating order -- reported
# as a match rate, not a per-case hard assertion, since all three are independent greedy
# searches over AICc with different MLE optimizers.
using DelimitedFiles

if get(ENV, "TSANALYTICS_FULL_TESTS", "1") == "1"
@testset "auto_arima bulk (20 cases, vs real pmdarima.auto_arima and R forecast::auto.arima)" begin
    cases = [
        ("case00_p0d0q1_seed1", (0, 0, 1), (0, 0, 0), (0, 0, 0)),
        ("case01_p0d0q1_seed2", (0, 0, 1), (0, 0, 0), (0, 0, 0)),
        ("case02_p0d0q1_seed3", (0, 0, 1), (0, 0, 1), (0, 0, 1)),
        ("case03_p0d0q2_seed1", (0, 0, 2), (2, 0, 3), (1, 0, 2)),
        ("case04_p0d0q2_seed2", (0, 0, 2), (0, 0, 0), (0, 0, 0)),
        ("case05_p0d0q2_seed3", (0, 0, 2), (2, 0, 0), (2, 0, 0)),
        ("case06_p0d1q1_seed1", (0, 1, 1), (0, 1, 0), (0, 1, 0)),
        ("case07_p0d1q1_seed2", (0, 1, 1), (0, 1, 0), (0, 1, 0)),
        ("case08_p0d1q1_seed3", (0, 1, 1), (0, 1, 1), (0, 1, 1)),
        ("case09_p0d1q2_seed1", (0, 1, 2), (2, 1, 3), (1, 1, 2)),
        ("case10_p0d1q2_seed2", (0, 1, 2), (0, 1, 0), (0, 1, 0)),
        ("case11_p0d1q2_seed3", (0, 1, 2), (1, 1, 0), (1, 1, 0)),
        ("case12_p0d2q1_seed1", (0, 2, 1), (0, 2, 0), (0, 2, 0)),
        ("case13_p0d2q1_seed2", (0, 2, 1), (0, 2, 0), (0, 2, 0)),
        ("case14_p0d2q1_seed3", (0, 2, 1), (0, 2, 1), (0, 2, 1)),
        ("case15_p0d2q2_seed1", (0, 2, 2), (1, 2, 2), (1, 2, 2)),
        ("case16_p0d2q2_seed2", (0, 2, 2), (0, 2, 0), (0, 2, 0)),
        ("case17_p0d2q2_seed3", (0, 2, 2), (1, 2, 0), (1, 2, 0)),
        ("case18_p1d0q0_seed1", (1, 0, 0), (1, 0, 0), (1, 0, 0)),
        ("case19_p1d0q0_seed2", (1, 0, 0), (1, 0, 0), (0, 0, 0)),
    ]
    py_matches = 0
    r_matches = 0
    for (case, true_order, py_order, r_order) in cases
        y = vec(readdlm(joinpath(@__DIR__, "verification", "autoarima", "bulk", "data", case * ".csv"), ','; skipstart=1))
        m = auto_arima(y; seasonal=false, stepwise=true, max_p=3, max_q=3, max_d=2)
        @test m isa ArimaModel
        @test m.arma.converged
        jl_order = (length(m.arma.ar), m.d, length(m.arma.ma))
        jl_order == py_order && (py_matches += 1)
        jl_order == r_order && (r_matches += 1)
    end
    py_match_rate = py_matches / length(cases)
    r_match_rate = r_matches / length(cases)
    @info "auto_arima bulk: selected_order match rate" py_match_rate r_match_rate
    # Both are independent greedy AICc searches with different MLE optimizers -- exact
    # agreement on every case isn't expected (see handoff section 6's own framing); a
    # majority match rate is the meaningful, checkable bar. R and Python's OWN searches
    # only agree with each other on 17/20 (85%) of these cases --
    # the floor below is calibrated against that, not against 100% three-way agreement.
    @test py_match_rate >= 0.6  # observed 0.85 (17/20) on real pmdarima.auto_arima
    @test r_match_rate >= 0.6   # observed 0.85 (17/20) on real R forecast::auto.arima
end
end
