# Generated by test/verification/garch/bulk/gen_julia_test.py -- do not edit by hand.
#
# Ground truth: real arch.arch_model (5.1.0, pip-installed) on 24 synthetic GARCH(1,1)
# series regenerated from the Stage 7.1 handoff's own bulk-grid description (section 6:
# 8 true (omega,alpha,beta) combinations x 3 seeds, n=800) -- the handoff's own
# garch_100cases_python.json has aggregate results only, no underlying series, so this
# generates fresh ones and fits them for real rather than trying to reproduce that file's
# exact numbers.
#
# Accuracy criterion: match what arch_model itself converges to on the same data (both are
# independent MLE searches over the same likelihood surface), not the true generating
# parameters -- the handoff's own 24-case run found even the reference doesn't recover
# those exactly (mean abs error 0.0388).
using DelimitedFiles

if get(ENV, "TSANALYTICS_FULL_TESTS", "1") == "1"
@testset "fit_garch bulk (24 cases, vs real arch.arch_model)" begin
    cases = [
        ("case00_o0.05_a0.05_b0.9_seed1", (0.17548088055274158, 0.072225263179663, 0.7482785478843929), -1121.8014999777292),
        ("case01_o0.05_a0.05_b0.9_seed2", (0.053681198031376366, 0.025621658361513783, 0.9219361798171405), -1145.1320394983284),
        ("case02_o0.05_a0.05_b0.9_seed3", (0.032811109388750606, 0.03813218565131879, 0.9299234619052977), -1141.1253945839535),
        ("case03_o0.05_a0.1_b0.85_seed1", (0.10944394343478778, 0.12865947355827184, 0.7566051717943582), -1092.3490704639075),
        ("case04_o0.05_a0.1_b0.85_seed2", (0.05843741885147697, 0.07152426543227605, 0.8701046219022492), -1121.71654030826),
        ("case05_o0.05_a0.1_b0.85_seed3", (0.03268532144142105, 0.07582867133670347, 0.892377118868215), -1121.3298754967568),
        ("case06_o0.05_a0.15_b0.8_seed1", (0.08915648467284572, 0.18584944819229207, 0.7191922536674448), -1051.6357470954038),
        ("case07_o0.05_a0.15_b0.8_seed2", (0.05887568612627003, 0.11991433121082057, 0.819638274978608), -1083.5046749971307),
        ("case08_o0.05_a0.15_b0.8_seed3", (0.03330059009776396, 0.11285077877305967, 0.8544125685080695), -1086.958229947921),
        ("case09_o0.1_a0.05_b0.85_seed1", (0.2567717249682613, 0.0737994842196435, 0.6668719412011748), -1127.7609133659612),
        ("case10_o0.1_a0.05_b0.85_seed2", (0.623026582033555, 0.06189625965270624, 0.33370284877185974), -1145.4874181191378),
        ("case11_o0.1_a0.05_b0.85_seed3", (0.045095528819002244, 0.027641016486337728, 0.9279716496526933), -1139.7594272487224),
        ("case12_o0.1_a0.1_b0.8_seed1", (0.19000982968900848, 0.1307957275028634, 0.6760097176790681), -1113.114775172785),
        ("case13_o0.1_a0.1_b0.8_seed2", (0.2800525065311741, 0.09510496110442986, 0.6287129155830649), -1134.3005995875783),
        ("case14_o0.1_a0.1_b0.8_seed3", (0.05214320601875541, 0.060488920508145576, 0.8878008960402614), -1128.1755534011054),
        ("case15_o0.1_a0.15_b0.75_seed1", (0.15916948372566267, 0.1861150541879362, 0.6518076129985242), -1092.0257452523297),
        ("case16_o0.1_a0.15_b0.75_seed2", (0.16892277574334322, 0.13208626805290358, 0.6981544407740659), -1114.4215184262562),
        ("case17_o0.1_a0.15_b0.75_seed3", (0.058008318302987916, 0.09561000665810185, 0.8461003081934368), -1109.0645686773798),
        ("case18_o0.02_a0.08_b0.88_seed1", (0.04997159216260443, 0.10281892199878664, 0.7920902828661893), -821.7118691052286),
        ("case19_o0.02_a0.08_b0.88_seed2", (0.023395385842883896, 0.054511676979081006, 0.8990637954510405), -852.5502720581163),
        ("case20_o0.02_a0.08_b0.88_seed3", (0.01406087054697815, 0.06430774242524798, 0.9085704780926144), -852.8761145155655),
        ("case21_o0.02_a0.12_b0.82_seed1", (0.03902085164045875, 0.1525969431766279, 0.7252393190742995), -646.8536011881397),
        ("case22_o0.02_a0.12_b0.82_seed2", (0.023947951568642586, 0.09005201785723485, 0.837796351830318), -674.8174123723888),
        ("case23_o0.02_a0.12_b0.82_seed3", (0.012606068790576326, 0.08699555413415545, 0.8758513746492538), -673.5490047821958),
    ]
    abs_errors = Float64[]
    for (case, py_fitted, py_loglik) in cases
        e = vec(readdlm(joinpath(@__DIR__, "verification", "garch", "bulk", "data", case * ".csv"), ','; skipstart=1))
        m = fit_garch(e, 1, 1; mean_spec=:zero, cov_type=:robust)
        @test m.converged
        jl_fitted = (m.omega, m.alpha[1], m.beta[1])
        append!(abs_errors, abs.(collect(jl_fitted) .- collect(py_fitted)))
        # loglik at Julia's own optimum should be at least as good as Python's --
        # both are MLE searches on the identical likelihood surface
        @test m.loglik >= py_loglik - 1e-2
    end
    mean_err = sum(abs_errors) / length(abs_errors)
    @info "fit_garch bulk: |Julia - Python fitted params| " mean_err
    # Both converge to the same likelihood surface's optimum on identical data --
    # a much tighter bar than matching the true generating parameters (handoff's own
    # 24-case run: mean abs error to TRUE params was 0.0388).
    @test mean_err < 0.01
end
end
