suppressMessages(library(rugarch))
e <- as.numeric(read.csv("garch_bench_data.csv", header=FALSE)[,1])
spec <- ugarchspec(variance.model=list(model="sGARCH", garchOrder=c(1,1)),
                   mean.model=list(armaOrder=c(0,0), include.mean=FALSE), distribution.model="norm")
f <- ugarchfit(spec, e, solver="solnp")
cat("=== CLASSICAL se/tval (matcoef) ===\n"); print(f@fit$matcoef)
cat("\n=== ROBUST se/tval (robust.matcoef) ===\n"); print(f@fit$robust.matcoef)
cat("\n=== ratio robust/classical se ===\n"); print(f@fit$robust.se.coef / f@fit$se.coef)
cat("\n=== Weighted Ljung-Box, standardized residuals ===\n")
out <- capture.output(show(f)); i <- grep("Weighted Ljung-Box Test on Standardized Residuals", out)
cat(paste(out[i:(i+6)], collapse="\n"), "\n")
cat("\n=== Weighted Ljung-Box, squared residuals ===\n")
i <- grep("Weighted Ljung-Box Test on Standardized Squared Residuals", out)
cat(paste(out[i:(i+6)], collapse="\n"), "\n")
cat("\n=== rugarch plot(which=) menu ===\n")
cat(paste(capture.output(print(rugarch:::.plotgarchfit))[1:6], collapse="\n"), "\n")
