options(digits=12)
y <- scan("ax_y.csv", quiet=TRUE); x <- scan("ax_x.csv", quiet=TRUE); xf <- scan("ax_xf.csv", quiet=TRUE)
m <- arima(y, order=c(1,0,0), xreg=x)
cat("R arima(y, order=c(1,0,0), xreg=x)\n")
cat("  coef :", format(round(as.numeric(m$coef),10)), "\n")
cat("  names:", names(m$coef), "\n")
cat("  se   :", format(round(sqrt(diag(m$var.coef)),10)), "\n")
cat("  loglik:", format(m$loglik, nsmall=8), "  aic:", format(m$aic, nsmall=6), "\n")
p <- predict(m, n.ahead=10, newxreg=xf)
cat("  forecast[1:5] :", format(round(as.numeric(p$pred)[1:5],10)), "\n")
cat("  se[1:5]       :", format(round(as.numeric(p$se)[1:5],10)), "\n")
