"""
Merges python_results.json (real arch.arch_model ground truth, see
gen_and_fit_python.py) into test/test_garch_bulk.jl.

Accuracy criterion matches the handoff's own honest framing (section 6):
GARCH MLE has real finite-sample noise even for the reference implementation
(the handoff's own 24-case run: mean abs parameter recovery error 0.0388,
median 0.0317, against the TRUE generating parameters) -- so this checks
Julia's fit against what Python's own arch_model converged to on the same
data (a tight, meaningful bar, since both should find the same likelihood
surface optimum), not against the unknowable-in-practice true parameters.
"""
import json
import os

DIR = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(DIR, "..", "..", "..", "test_garch_bulk.jl")

with open(os.path.join(DIR, "python_results.json")) as f:
    results = json.load(f)

case_lines = ["    cases = ["]
for r in results:
    case = r["case"]
    fitted = tuple(r["fitted"])
    loglik = r["loglik"]
    case_lines.append(f'        ("{case}", {fitted}, {loglik}),')
case_lines.append("    ]")

n = len(results)
lines = []
lines.append("using DelimitedFiles")
lines.append("")
lines.append("if get(ENV, \"TSANALYTICS_FULL_TESTS\", \"1\") == \"1\"")
lines.append(f'@testset "fit_garch bulk ({n} cases, vs real arch.arch_model)" begin')
lines.extend(case_lines)
lines.append("    abs_errors = Float64[]")
lines.append("    for (case, py_fitted, py_loglik) in cases")
lines.append('        e = vec(readdlm(joinpath(@__DIR__, "verification", "garch", "bulk", "data", case * ".csv"), \',\'; skipstart=1))')
lines.append("        m = fit_garch(e, 1, 1; mean_spec=:zero, cov_type=:robust)")
lines.append("        @test m.converged")
lines.append("        jl_fitted = (m.omega, m.alpha[1], m.beta[1])")
lines.append("        append!(abs_errors, abs.(collect(jl_fitted) .- collect(py_fitted)))")
lines.append("        # loglik at Julia's own optimum should be at least as good as Python's --")
lines.append("        # both are MLE searches on the identical likelihood surface")
lines.append("        @test m.loglik >= py_loglik - 1e-2")
lines.append("    end")
lines.append("    mean_err = sum(abs_errors) / length(abs_errors)")
lines.append('    @info "fit_garch bulk: |Julia - Python fitted params| " mean_err')
lines.append("    # Both converge to the same likelihood surface's optimum on identical data --")
lines.append("    # a much tighter bar than matching the true generating parameters (handoff's own")
lines.append("    # 24-case run: mean abs error to TRUE params was 0.0388).")
lines.append("    @test mean_err < 0.01")
lines.append("end")
lines.append("end")
lines.append("")

header = [
    "# Generated by test/verification/garch/bulk/gen_julia_test.py -- do not edit by hand.",
    "#",
    "# Ground truth: real arch.arch_model (5.1.0, pip-installed) on 24 synthetic GARCH(1,1)",
    "# series regenerated from the Stage 7.1 handoff's own bulk-grid description (section 6:",
    "# 8 true (omega,alpha,beta) combinations x 3 seeds, n=800) -- the handoff's own",
    "# garch_100cases_python.json has aggregate results only, no underlying series, so this",
    "# generates fresh ones and fits them for real rather than trying to reproduce that file's",
    "# exact numbers.",
    "#",
    "# Accuracy criterion: match what arch_model itself converges to on the same data (both are",
    "# independent MLE searches over the same likelihood surface), not the true generating",
    "# parameters -- the handoff's own 24-case run found even the reference doesn't recover",
    "# those exactly (mean abs error 0.0388).",
    "",
]

out_text = "\n".join(header) + "\n".join(lines)

with open(OUT, "w") as f:
    f.write(out_text)

print(f"Wrote {n} cases to {OUT}")
