# Fits the same 20 CSVs (test/verification/autoarima/bulk/data/, generated by
# gen_and_fit_python.py) with real R forecast::auto.arima, for a genuine dual
# R+Python cross-check -- forecast IS installed and reachable this session
# (confirmed directly, not assumed; earlier stages' "CRAN unreachable"
# boundary note doesn't hold here).
library(forecast)
library(jsonlite)

args <- commandArgs(trailingOnly = FALSE)
script_path <- sub("--file=", "", args[grep("--file=", args)])
DIR <- dirname(normalizePath(script_path))
DATA_DIR <- file.path(DIR, "data")

py_results <- fromJSON(file.path(DIR, "python_results.json"))

results <- list()
for (i in seq_len(nrow(py_results))) {
    case <- py_results$case[i]
    y <- scan(file.path(DATA_DIR, paste0(case, ".csv")), skip = 1, quiet = TRUE)
    m <- auto.arima(y, seasonal = FALSE, stepwise = TRUE,
                     max.p = 3, max.q = 3, max.d = 2, ic = "aicc")
    ord <- arimaorder(m)
    r_order <- c(unname(ord["p"]), unname(ord["d"]), unname(ord["q"]))
    result <- list(case = case, r_order = r_order, r_aic = AIC(m))
    results[[i]] <- result
    cat(case, ": r_order=(", paste(r_order, collapse = ","), ") aic=", AIC(m), "\n")
}

write(toJSON(results, auto_unbox = TRUE, pretty = TRUE), file.path(DIR, "r_results.json"))
cat("\nWrote", length(results), "cases to r_results.json\n")
