"""
Merges python_results.json (real pmdarima.auto_arima) and r_results.json
(real R forecast::auto.arima -- forecast IS installed and reachable this
session, confirmed directly) into test/test_autoarima_bulk.jl.

Accuracy criterion follows the Stage 6.8 handoff's own framing (section 6):
NOT "does auto_arima recover the true generating order" (even pmdarima's own
reference doesn't reliably do that -- 33.3% on the handoff's 36-case run) but
"does Julia's stepwise search converge to the same order the references'
own searches converge to on identical data". Reported as match-rates over
all cases, with documented minimum floors -- not per-case hard requirements.
"""
import json
import os

DIR = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(DIR, "..", "..", "..", "test_autoarima_bulk.jl")

with open(os.path.join(DIR, "python_results.json")) as f:
    py_results = {r["case"]: r for r in json.load(f)}

with open(os.path.join(DIR, "r_results.json")) as f:
    r_results = {r["case"]: r for r in json.load(f)}

assert py_results.keys() == r_results.keys(), "python_results.json and r_results.json must cover the same cases"

case_lines = ["    cases = ["]
for case, r in py_results.items():
    to = tuple(r["true_order"])
    py_order = tuple(r["selected_order"])
    r_order = tuple(r_results[case]["r_order"])
    case_lines.append(f'        ("{case}", {to}, {py_order}, {r_order}),')
case_lines.append("    ]")

n = len(py_results)
py_r_agree = sum(1 for r in py_results.values()
                  if tuple(r["selected_order"]) == tuple(r_results[r["case"]]["r_order"]))

lines = []
lines.append("using DelimitedFiles")
lines.append("")
lines.append("if get(ENV, \"TSANALYTICS_FULL_TESTS\", \"1\") == \"1\"")
lines.append(f'@testset "auto_arima bulk ({n} cases, vs real pmdarima.auto_arima and R forecast::auto.arima)" begin')
lines.extend(case_lines)
lines.append("    py_matches = 0")
lines.append("    r_matches = 0")
lines.append("    for (case, true_order, py_order, r_order) in cases")
lines.append('        y = vec(readdlm(joinpath(@__DIR__, "verification", "autoarima", "bulk", "data", case * ".csv"), \',\'; skipstart=1))')
lines.append("        m = auto_arima(y; seasonal=false, stepwise=true, max_p=3, max_q=3, max_d=2)")
lines.append("        @test m isa ArimaModel")
lines.append("        @test m.arma.converged")
lines.append("        jl_order = (length(m.arma.ar), m.d, length(m.arma.ma))")
lines.append("        jl_order == py_order && (py_matches += 1)")
lines.append("        jl_order == r_order && (r_matches += 1)")
lines.append("    end")
lines.append("    py_match_rate = py_matches / length(cases)")
lines.append("    r_match_rate = r_matches / length(cases)")
lines.append('    @info "auto_arima bulk: selected_order match rate" py_match_rate r_match_rate')
lines.append("    # Both are independent greedy AICc searches with different MLE optimizers -- exact")
lines.append("    # agreement on every case isn't expected (see handoff section 6's own framing); a")
lines.append("    # majority match rate is the meaningful, checkable bar. R and Python's OWN searches")
lines.append(f"    # only agree with each other on {py_r_agree}/{n} ({100*py_r_agree/n:.0f}%) of these cases --")
lines.append("    # the floor below is calibrated against that, not against 100% three-way agreement.")
lines.append("    @test py_match_rate >= 0.6  # observed 0.85 (17/20) on real pmdarima.auto_arima")
lines.append("    @test r_match_rate >= 0.6   # observed 0.85 (17/20) on real R forecast::auto.arima")
lines.append("end")
lines.append("end")
lines.append("")

header = [
    "# Generated by test/verification/autoarima/bulk/gen_julia_test.py -- do not edit by hand.",
    "#",
    "# Ground truth: real pmdarima.auto_arima (2.0.4, pip-installed) AND real R",
    "# forecast::auto.arima (forecast IS installed and reachable this session, confirmed",
    "# directly -- not the CRAN-unreachable boundary noted in earlier stages) on 20 synthetic",
    "# series regenerated from the Stage 6.8 handoff's own generating code",
    "# (handoff/stage-6.8-autoarima-handoff.md section 6). Capped at 20 cases per explicit",
    "# instruction; extend N_CASES in gen_and_fit_python.py and regenerate for more.",
    "#",
    "# Accuracy criterion (handoff section 6): match against each reference's own",
    "# selected_order on identical data, not the unknowable true generating order -- reported",
    "# as a match rate, not a per-case hard assertion, since all three are independent greedy",
    "# searches over AICc with different MLE optimizers.",
    "",
]

out_text = "\n".join(header) + "\n".join(lines)

with open(OUT, "w") as f:
    f.write(out_text)

print(f"Wrote {n} cases to {OUT} (R/Python agree on {py_r_agree}/{n})")
