"""
Merges python_results.json (real arch.arch_model ground truth, see
gen_and_fit_python.py) into test/test_garch_gjr_egarch_bulk.jl.

Accuracy criterion matches Stage 7.1's own bulk sweep: check Julia's fit
against what Python's own arch_model converged to on the same data, not
the true generating parameters (both are independent MLE searches over
the same likelihood surface).
"""
import json
import os

DIR = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(DIR, "..", "..", "..", "test_garch_gjr_egarch_bulk.jl")

with open(os.path.join(DIR, "python_results.json")) as f:
    results = json.load(f)

case_lines = ["    cases = ["]
for r in results:
    case = r["case"]
    model = r["model"]
    fitted = tuple(r["fitted"])
    loglik = r["loglik"]
    case_lines.append(f'        ("{case}", :{model}, {fitted}, {loglik}),')
case_lines.append("    ]")

n = len(results)
lines = []
lines.append("using DelimitedFiles")
lines.append("")
lines.append("if get(ENV, \"TSANALYTICS_FULL_TESTS\", \"1\") == \"1\"")
lines.append(f'@testset "fit_garch GJR/EGARCH bulk ({n} cases, vs real arch.arch_model)" begin')
lines.extend(case_lines)
lines.append("    abs_errors = Float64[]")
lines.append("    n_converged = 0")
lines.append("    for (case, model, py_fitted, py_loglik) in cases")
lines.append('        e = vec(readdlm(joinpath(@__DIR__, "verification", "garch", "bulk_gjr_egarch", "data", case * ".csv"), \',\'; skipstart=1))')
lines.append("        m = fit_garch(e, 1, 1; model=model, mean_spec=:zero, cov_type=:robust)")
lines.append("        m.converged && (n_converged += 1)")
lines.append("        jl_fitted = (m.omega, m.alpha[1], m.gamma[1], m.beta[1])")
lines.append("        append!(abs_errors, abs.(collect(jl_fitted) .- collect(py_fitted)))")
lines.append("    end")
lines.append("    mean_err = sum(abs_errors) / length(abs_errors)")
lines.append('    @info "fit_garch GJR/EGARCH bulk: |Julia - Python fitted params|, convergence" mean_err n_converged')
lines.append("    @test n_converged == length(cases)")
lines.append("    # Both converge to the same likelihood surface's optimum on identical data --")
lines.append("    # a much tighter bar than matching the true generating parameters (Stage 7.1's own")
lines.append("    # 24-case run found even the reference doesn't recover those exactly).")
lines.append("    @test mean_err < 0.02")
lines.append("end")
lines.append("end")
lines.append("")

header = [
    "# Generated by test/verification/garch/bulk_gjr_egarch/gen_julia_test.py -- do not edit",
    "# by hand.",
    "#",
    "# Ground truth: real arch.arch_model (5.1.0, pip-installed) on 48 synthetic GJR-GARCH/",
    "# EGARCH series regenerated from the Stage 7.2 handoff's own bulk-grid description",
    "# (section 5: 8 true parameter combinations x 3 seeds x 2 model types, n=1500) --",
    "# extends Stage 7.1's exact 24-case methodology to both new asymmetric variants.",
    "#",
    "# Accuracy criterion: match what arch_model itself converges to on the same data, not",
    "# the true generating parameters -- same honest framing as Stage 7.1's own bulk sweep.",
    "",
]

out_text = "\n".join(header) + "\n".join(lines)

with open(OUT, "w") as f:
    f.write(out_text)

print(f"Wrote {n} cases to {OUT}")
