options(digits=12)
suppressWarnings(suppressMessages(library(forecast)))
y <- log(scan("airp.csv", quiet=TRUE))
ty <- ts(y, frequency=12)
cat("seas.heuristic :", format(round(forecast:::seas.heuristic(ty),10)), "\n")
cat("nsdiffs(seas)  :", nsdiffs(ty, test="seas"), "\n")
o <- forecast:::ocsb.test(ty, maxlag=3, lag.method="AIC")
cat("ocsb stat      :", format(round(as.numeric(o$statistics),10)), "\n")
cat("ocsb critical  :", format(round(as.numeric(o$critical),10)), "\n")
cat("ocsb lag.order :", o$lag.order, "\n")
cat("nsdiffs(ocsb)  :", nsdiffs(ty, test="ocsb"), "\n")
